/// A report containing performance metrics for an API request.
///
/// This class encapsulates timing and metadata information collected
/// during the execution of an API request. It's generated by
/// [ApiRequestPerformance] and can be accessed via
/// [RequestAction.performanceReport].
///
/// ## Usage
///
/// Performance reports are automatically generated when requests are executed:
///
/// ```dart
/// final result = await GetPostsAction().execute();
/// final report = action.performanceReport;
/// 
/// if (report != null) {
///   print('Request completed in: ${report.duration?.inMilliseconds}ms');
///   print('Action: ${report.actionName}');
///   print('URL: ${report.fullPath}');
/// }
/// ```
///
/// ## Metrics Included
///
/// - **Action Name**: The class name of the request action
/// - **Full Path**: Complete URL that was requested
/// - **Duration**: Time taken from request start to completion
///
/// ## Performance Analysis
///
/// Use reports to identify slow requests and optimize performance:
///
/// ```dart
/// final report = action.performanceReport;
/// if (report?.duration != null && report!.duration!.inSeconds > 5) {
///   logger.warn('Slow request detected: ${report.actionName}');
///   analytics.track('slow_request', {
///     'action': report.actionName,
///     'duration_ms': report.duration!.inMilliseconds,
///     'url': report.fullPath,
///   });
/// }
/// ```
///
/// ## Global Performance Monitoring
///
/// Access all performance reports via [ApiRequestPerformance]:
///
/// ```dart
/// final performance = ApiRequestPerformance.instance;
/// print('All request performance:');
/// print(performance.toString()); // Prints all reports
/// ```
///
/// See also:
/// - [ApiRequestPerformance] for the performance tracking system
/// - [RequestAction.performanceReport] for accessing individual reports
class PerformanceReport {
  /// The name of the action class that made the request.
  ///
  /// This is typically the runtime type of the [RequestAction] subclass,
  /// such as "GetPostsAction" or "CreateUserAction".
  ///
  /// Example:
  /// ```dart
  /// print('Action: ${report.actionName}'); // "Action: GetPostsAction"
  /// ```
  final String? actionName;
  
  /// The complete URL that was requested.
  ///
  /// This includes the base URL and the resolved path with any dynamic
  /// variables substituted. Query parameters may or may not be included
  /// depending on the request type.
  ///
  /// Example:
  /// ```dart
  /// print('URL: ${report.fullPath}'); // "URL: https://api.example.com/posts/123"
  /// ```
  final String? fullPath;
  
  /// The total time taken to complete the request.
  ///
  /// This duration is measured from the moment [ApiRequestPerformance.startTrack]
  /// is called (just before HTTP request execution) until
  /// [ApiRequestPerformance.endTrack] is called (after response processing).
  ///
  /// The duration includes:
  /// - Network request time
  /// - Response parsing time
  /// - Any interceptor processing time
  ///
  /// Example:
  /// ```dart
  /// if (report.duration != null) {
  ///   print('Took: ${report.duration!.inMilliseconds}ms');
  /// }
  /// ```
  final Duration? duration;

  /// Creates a new [PerformanceReport] with the specified metrics.
  ///
  /// Parameters:
  /// - [actionName]: Required name/type of the action that made the request
  /// - [duration]: Optional duration of the request (null for incomplete requests)
  /// - [fullPath]: Optional full URL that was requested
  ///
  /// This constructor is typically called by [ApiRequestPerformance] and
  /// not used directly by application code.
  PerformanceReport({required this.actionName, this.duration, this.fullPath});

  /// Returns a human-readable string representation of the performance report.
  ///
  /// The format includes the URL, duration, and action name for easy debugging
  /// and logging.
  ///
  /// Example output:
  /// ```
  /// https://api.example.com/posts end in: 0:00:01.234567 in GetPostsAction
  /// ```
  ///
  /// If duration is null (request not completed), it will show "null".
  @override
  String toString() {
    return "$fullPath end in: ${duration.toString()} in $actionName";
  }
}
